### ISSUE TITLE
Emitter doesn't work properly with Event Stream

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-runner-http#56]
Looks like comparing with `current ob_level` prevents emitter to flush the main stream
https://github.com/yiisoft/yii-runner-http/blob/23d89de28a761ea06727ee895cec80c2dfcd309e/src/SapiEmitter.php#L112

In the dev panel I see results only when event stream times out.

**Comment by vjik** [comment]
Problem not here:

![Анимация](https://github.com/yiisoft/yii-runner-http/assets/525501/9ca0c6e1-e0f2-4b0a-a158-ae049c528b1e)
