### ISSUE TITLE
Exit with code `1` on error or exception

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-runner-http#75]
I suppose to need to register shutdown function on error/exception:

```php
register_shutdown_function(static function (): void { 
     exit(1); 
}); 
 ```

**Comment by samdark** [comment]
No need for it. See https://github.com/yiisoft/error-handler/pull/123

**Comment by xepozz** [comment]
No need for it in error-handler. Here is more expected place for the handler

**Comment by samdark** [comment]
@xepozz unfortunately, not really achievable for the cases it's called now:

1. Errors not handled by runner's try-catch (or `ErrorCatcher`) which is usually not the case.
2. Fatal errors that are caught only at shutdown and can't be converted to exceptions.
